import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by Admin",
};

const AuthLayout = (props: { children: React.ReactNode }) => {
  return <div>{props.children}</div>;
};

export default AuthLayout;
