import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by Dashboard",
};

const DashboardLayout = (props: { children: React.ReactNode }) => {
  return <div>{props.children}</div>;
};

export default DashboardLayout;
